"use client"

import { useEffect, useState } from "react"
import { QRCodeCanvas } from "qrcode.react"

export default function CertificatePage(){

 const API =
 process.env.NEXT_PUBLIC_API_URL ||
 "http://localhost:5000"

 const BASE =
 process.env.NEXT_PUBLIC_BASE_URL ||
 "http://localhost:3000"

 const [farmer,setFarmer] = useState<any>(null)

 useEffect(()=>{

 const farmerId = localStorage.getItem("farmerId")

 if(!farmerId) return

 fetch(`${API}/api/farmer/${farmerId}`)
 .then(res=>res.json())
 .then(setFarmer)

 },[])

 function downloadCertificate(){

 const farmerId = localStorage.getItem("farmerId")

 window.open(
 `${API}/api/certificate/${farmerId}`,
 "_blank"
 )

 }

 if(!farmer){

 return(
 <div className="text-emerald-700 p-10">
 Loading certificate...
 </div>
 )

 }

 const certificateId =
 "HT-CERT-" + farmer._id.slice(-6).toUpperCase()

 const issueDate =
 new Date().toLocaleDateString()

 return(

 <div className="min-h-screen bg-emerald-50 text-emerald-950 flex justify-center items-center p-10">

 <div className="bg-white border border-emerald-200 rounded-3xl p-10 max-w-3xl w-full shadow-sm relative">

 {/* SEAL BACKGROUND */}

 <div className="absolute top-6 right-6 text-[100px] opacity-10">
 🌿
 </div>


 {/* HEADER */}

 <div className="text-center mb-8">

 <h1 className="text-3xl font-bold text-emerald-900">
 HERBTRACKING AUTHORITY
 </h1>

 <p className="text-emerald-700 text-sm">
 Herbal Supply Chain Verification Board (India)
 </p>

 </div>


 <h2 className="text-center text-2xl font-semibold mb-10 text-emerald-800">
 Farm Authenticity Certificate
 </h2>


 <div className="text-center space-y-4 text-lg text-emerald-900">

 <p>This certificate confirms that</p>

 <p className="text-3xl font-bold text-emerald-700">
 {farmer.name}
 </p>

 <p>owner of</p>

 <p className="text-xl font-semibold">
 {farmer.farmName}
 </p>

 <p>located in</p>

 <p className="text-xl">
 {farmer.location}
 </p>

 <p>
 is a verified herbal producer within the
 HerbTracking national traceability network.
 </p>

 </div>


 <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-10 text-sm">

 <div>
 <p className="text-emerald-600">Certificate ID</p>
 <p className="font-semibold text-emerald-900">{certificateId}</p>
 </div>

 <div>
 <p className="text-emerald-600">Issue Date</p>
 <p className="font-semibold text-emerald-900">{issueDate}</p>
 </div>

 <div>
 <p className="text-emerald-600">Experience</p>
 <p className="font-semibold text-emerald-900">
 {farmer.experience} years
 </p>
 </div>

 <div>
 <p className="text-emerald-600">Farmer Rating</p>
 <p className="font-semibold text-emerald-900">
 ⭐ {farmer.rating}/5
 </p>
 </div>

 </div>


 <div className="flex flex-col md:flex-row justify-between items-start md:items-end mt-12 gap-8">

 <div>

 <p className="text-emerald-600 text-sm">
 Authorized By
 </p>

 <p className="text-xl font-semibold mt-1 text-emerald-900">
 HerbTracking Authority
 </p>

 <div className="mt-2 border-t border-emerald-300 w-40"></div>

 <p className="text-xs mt-1 text-emerald-600">
 Digital Verification Signature
 </p>

 </div>


 <div className="text-center">

 <div className="w-24 h-24 rounded-full border-2 border-emerald-600 flex items-center justify-center text-emerald-700 text-xs font-bold rotate-3 bg-emerald-50">

 VERIFIED
 </div>

 <p className="text-xs text-emerald-600 mt-2">
 Official Seal
 </p>

 </div>


 <div className="text-center">

 <p className="text-emerald-600 text-sm mb-2">
 Verification QR
 </p>

 <QRCodeCanvas
 value={`${BASE}/trace/farmer/${farmer._id}`}
 size={90}
 />

 </div>

 </div>


 <div className="text-center text-xs text-emerald-600 mt-10">

 <p>
 This certificate is digitally generated by the
 HerbTracking blockchain supply chain system.
 </p>

 <p>
 Tampering or duplication is strictly prohibited.
 </p>

 </div>


 <div className="mt-8 text-center">

 <button
 onClick={downloadCertificate}
 className="bg-emerald-600 hover:bg-emerald-700 text-white px-6 py-3 rounded-xl font-semibold"
 >

 Download Official Certificate

 </button>

 </div>

 </div>

 </div>

 )

}
